### ISSUE TITLE
JS-Controller 3.3 - warning wrong type

### ISSUE THREAD

**Issue by kueppert** [iobroker-community-adapters/ioBroker.yeelight-2#90]
yeelight-2.0 | 2021-04-30 09:56:04.589 | warn | (21133) State value to set for "yeelight-2.0.YeelightMeteorite.control.ct" has wrong type "string" but has to be "number"

yeelight-2.0 | 2021-04-30 09:56:04.587 | warn | (21133) State value to set for "yeelight-2.0.YeelightMeteorite.control.active_bright" has wrong type "string" but has to be "number"

**Comment by TheBrain26** [comment]
Same Issues

ioBroker/ioBroker.js-controller#1299 (comment)

**Comment by TDCroPower** [comment]
@TheBrain26 It is the same problem, but it affects this adapter and needs an update of the set data points from the adapter!

**Comment by Lumumba76** [comment]
Workaround:
![workaround](https://user-images.githubusercontent.com/20858466/125784492-7fd21cbd-b282-4aa0-a176-97aa1d61356e.PNG)

**Comment by MeisterTR** [comment]
fixed on git

**Comment by maxpd1** [comment]
Will it be released as I still have the problem with v 1.1.2
